import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "@/components/client-providers"
import Link from "next/link"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          <nav className="w-full flex items-center justify-center gap-6 py-4 border-b bg-background">
            <Link href="/dashboard" className="font-semibold">Dashboard</Link>
            <Link href="/meals">Meals</Link>
            <Link href="/health">Health</Link>
            <Link href="/recipes">Recipes</Link>
            <Link href="/food">Food</Link>
            <Link href="/profile">Profile</Link>
          </nav>
          {children}
        </ClientProviders>
      </body>
    </html>
  )
}
